# Generated by Django 2.1.4 on 2018-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统类型')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本')),
                ('alias', models.TextField(max_length=256, verbose_name='主机别名')),
                ('extranet_IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('Intranet_IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('ssh_port', models.CharField(default=22, max_length=16, verbose_name='SSH端口')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='CPU数量')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)')),
                ('disk', models.FloatField(blank=True, null=True, verbose_name='磁盘大小(GB)')),
                ('network_bandwidth', models.CharField(blank=True, max_length=64, null=True, verbose_name='网络带宽')),
                ('ssh_user', models.TextField(blank=True, max_length=256, null=True, verbose_name='远程登录用户')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
    ]
