# Generated by Django 2.1.4 on 2018-12-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统类型')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('alias', models.CharField(max_length=64, verbose_name='主机别名')),
                ('extranet_IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('intranet_IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('ssh_port', models.CharField(default=22, max_length=16, verbose_name='SSH端口')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='CPU数量')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)')),
                ('disk', models.FloatField(blank=True, null=True, verbose_name='磁盘大小(GB)')),
                ('network_bandwidth', models.CharField(blank=True, max_length=64, null=True, verbose_name='网络带宽(Mbps)')),
                ('ssh_user_root_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='root用户密码')),
                ('ssh_user_other', models.TextField(blank=True, max_length=256, null=True, verbose_name='其他远程登录用户')),
                ('ssh_user_other_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='其他远程用户密码')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('system', models.CharField(choices=[('mainnet', '主网环境'), ('testnet', '测试网环境'), ('develop', '开发环境'), ('others', '其他环境')], default='others', max_length=64, verbose_name='所属环境')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'ordering': ['-modified_time'],
            },
        ),
    ]
