# Generated by Django 2.1.4 on 2018-12-26 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
