# Generated by Django 2.1.4 on 2018-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181214_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='alias',
            field=models.CharField(max_length=64, verbose_name='主机别名'),
        ),
    ]
