# Generated by Django 2.1.4 on 2018-12-17 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181214_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='Intranet_IP',
            new_name='intranet_IP',
        ),
        migrations.AddField(
            model_name='server',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='最后修改时间'),
            preserve_default=False,
        ),
    ]
