# Generated by Django 2.1.4 on 2018-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181217_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='network_bandwidth',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='网络带宽(Mbps)'),
        ),
    ]
