# Generated by Django 2.1.4 on 2018-12-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181217_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='system',
            field=models.CharField(default='others', max_length=64, verbose_name='所属环境'),
        ),
    ]
