# Generated by Django 2.1.4 on 2018-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_server_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='system',
            field=models.CharField(choices=[('mainnet', '主网环境'), ('testnet', '测试网环境'), ('develop', '开发环境'), ('others', '其他环境')], default='others', max_length=64, verbose_name='所属环境'),
        ),
    ]
