# Generated by Django 2.1.4 on 2018-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20181218_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名'),
        ),
    ]
