# Generated by Django 2.1.4 on 2018-12-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_server_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=72)),
                ('password', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '服务器用户',
                'verbose_name_plural': '服务器用户',
                'ordering': ['-modified_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-modified_time'], 'verbose_name': '服务器', 'verbose_name_plural': '服务器'},
        ),
        migrations.AddField(
            model_name='serveruser',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server'),
        ),
    ]
