# Generated by Django 2.1.4 on 2018-12-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181213_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmDtring',
            new_name='ConfirmString',
        ),
    ]
